dictionary_pr/dictionary/urls.py
from django.urls import path, include
from dictionary.views import DictView, DictDetailView, Search, create, DictUpdateView, DictDeleteView

app_name = 'dictionary'


urlpatterns = [
    path('', DictView.as_view(), name='dict'),
    path('<int:pk>/', DictDetailView.as_view(), name='dict_detail'),
    path('search/', Search.as_view(), name='search'),
    path('create/', create, name='create'),
    path('<int:pk>/update', DictUpdateView.as_view(), name='dict_update'),
    path('<int:pk>/delete', DictDeleteView.as_view(), name='dict_delete'),
]

dictionary_pr/dictionary_pr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dictionary/', include('dictionary.urls', namespace='dictionary')),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dictionary_pr/dictionary/models.py
from django.db import models


class Word(models.Model):
    name = models.CharField('Название слова', max_length=64)
    text = models.TextField('Определение слова')
    photo = models.ImageField('Изображение', upload_to='images/')

    class Meta:
        verbose_name = 'Слово'
        verbose_name_plural = 'Слова'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/dictionary/{self.id}'

dictionary_pr/dictionary/forms.py
from django.forms import ModelForm, TextInput, Textarea, FileInput

from dictionary.models import Word


class DictForm(ModelForm):
    class Meta:
        model = Word
        fields = ['name', 'text', 'photo']

        widgets = {
            "name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Слово',
                'width': '500px'
            }),
            "text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Отпределение слова',
                'width': '500px'
            }),
            "photo": FileInput(attrs={
                'class': 'form-control',
                'placeholder': 'Изображение',
                'width': '500px'
            }),
        }

dictionary_pr/dictionary/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, UpdateView, DeleteView

from dictionary.forms import DictForm
from dictionary.models import Word


class DictView(ListView):
    paginate_by = 5
    model = Word
    template_name = 'dictionary/dictionary_list.html'
    context_object_name = 'dict'


class DictDetailView(DetailView):
    model = Word
    template_name = 'dictionary/dictionary_detail.html'
    context_object_name = 'dict_detail'


class Search(ListView):

    template_name = 'dictionary/dictionary_list.html'
    context_object_name = 'dict'
    paginate_by = 5

    def get_queryset(self):
        return Word.objects.filter(name__iregex=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        return context


def create(request):
    if request.method == 'POST':
        form = DictForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dictionary:dict')

    form = DictForm()

    data = {
        'form': form
    }
    return render(request, 'dictionary/create.html', data)


class DictUpdateView(UpdateView):
    model = Word
    template_name = 'dictionary/create.html'

    form_class = DictForm


class DictDeleteView(DeleteView):
    model = Word
    success_url = '/dictionary/'
    template_name = 'dictionary/dictionary_delete.html'

dictionary_pr/dictionary/templates/dictionary/create.html
{% extends 'root.html' %}

{% block content %}
    <div style="margin: 2%;">
        <h3>Добавление слова</h3><br>
        <form method="post" enctype="multipart/form-data" style="width: 50%;">
            {% csrf_token %}
            {{ form.name }}<br>
            {{ form.text }}<br>
            {{ form.photo }}<br>
            <button type="submit" class="btn btn-primary" style="font-size: 22px;">Добавить</button>
        </form>
    </div>
{% endblock %}

dictionary_pr/dictionary/templates/dictionary/dictionary_delete.html
{% extends 'root.html' %}

{% block content %}
    <div style="margin: 2%;">
        <h3>Удаление слова</h3><br>
        <form method="post" style="width: 50%;">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" style="font-size: 22px;">Удалить</button>
        </form>
    </div>
{% endblock %}

dictionary_pr/dictionary/templates/dictionary/dictionary_detail.html
{% extends 'root.html' %}

{% block content %}
    <div>
        <div class="card" style="width: 70%; margin: 2%;">
            <h5 class="card-header"><a style="text-decoration: none;" href="{% url 'dictionary:dict' %}"><i class="fa-solid fa-arrow-left"></i> Назад</a></h5>
            <div class="card-body">
                <p class="card-text" style="font-size: 20px;"><span style="font-weight: bold;">{{ dict_detail.name }}</span> - {{ dict_detail.text }}</p>
                <img style="width: 60%;" src="{{ dict_detail.photo.url }}"> <br><br>
                <a href="{% url 'dictionary:dict_update' dict_detail.id %}" class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i> Редактировать</a>
                <a href="{% url 'dictionary:dict_delete' dict_detail.id %}" class="btn btn-danger"><i class="fa-solid fa-circle-xmark"></i> Удалить</a>
            </div>
        </div>
    </div>
{% endblock %}

dictionary_pr/dictionary/templates/dictionary/dictionary_list.html
{% extends 'root.html' %}

{% block content %}
    <div style="margin: 2%;">

        <div class="d-flex justify-content-start">
            {% for el in dict %}
                <div class="card" style="width: 18rem; margin: 20px;">
                    <img class="card-img-top" src="{{ el.photo.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-text">{{ el.name }}</h5>
                        <a href="{% url 'dictionary:dict_detail' el.id %}" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <nav aria-label="Page navigation example" style="margin-top: 20px; margin-left: 2.5%;" class="">
            <ul class="pagination">
                {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                        <li class="page-item active"><p class="page-link">{{ p }}<span class="sr-only"></span></p></li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
        <div>
            <a href="{% url 'dictionary:create' %}" class="btn btn-primary" style="font-size: 24px;">Добавить слово</a>
        </div>
    </div>
{% endblock %}

dictionary_pr/templates/root.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="https://kit.fontawesome.com/f62ec13992.js" crossorigin="anonymous"></script>
</head>
<body>
    <header >
        <div class="d-flex align-items-center" style="background: #66B2FF; width: 100%; height: 110px; padding: 2%;">
                <form method="get" action="{% url 'dictionary:search' %}">
                    {% csrf_token %}
                    <input class="btn btn-light" type="search" name="q" placeholder="&#128269; Поиск" style="width: 400px; text-align: left;">
                    <button class="btn btn-primary" type="submit">Найти</button>
                </form>
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>